services:
  web-app:
    build: ./app
    container_name: node-crud-app
    ports:
      - "3000:3000"
    env_file:
      - ./app/.env
    depends_on:
      - db-mysql

  db-mysql:
    image: mysql:8
    container_name: mysql-crud-db
    environment:
      MYSQL_ROOT_PASSWORD: supersecretroot
      MYSQL_DATABASE: user_service_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-persistent-data:/var/lib/mysql

volumes:
  mysql-persistent-data: